source 'https://github.com/CocoaPods/Specs.git'

target 'AFSwipeToHide', :exclusive => true do
  pod "AFSwipeToHide", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AFSwipeToHide", :path => "../"

  
end
